import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class Exercise {
  final String id;
  final String title;
  final String description;
  final String duration;
  final int series;
  final int reps;
  final List<String> instructions;
  final String imageUrl;
  final IconData icon;
  final Color iconColor;
  final Color iconBgColor;
  final List<String> categories;
  final String difficulty;
  final String targetMuscles;

  const Exercise({
    required this.id,
    required this.title,
    required this.description,
    required this.duration,
    required this.series,
    required this.reps,
    required this.instructions,
    required this.imageUrl,
    required this.icon,
    required this.iconColor,
    required this.iconBgColor,
    required this.categories,
    required this.difficulty,
    required this.targetMuscles,
  });
}

// Datos de ejercicios
final List<Exercise> allExercises = [
  Exercise(
    id: '1',
    title: 'Flexión de Rodilla',
    description: 'Este ejercicio está diseñado para fortalecer los músculos cuádriceps y mejorar la flexibilidad de la rodilla. Es ideal para pacientes en rehabilitación post-operatoria o con problemas de movilidad.',
    duration: '30 min',
    series: 3,
    reps: 12,
    instructions: [
      'Siéntate en una silla con la espalda recta y los pies apoyados en el suelo.',
      'Extiende lentamente una pierna hasta que esté completamente recta.',
      'Mantén la posición durante 3-5 segundos, sintiendo la contracción en el cuádriceps.',
      'Baja lentamente la pierna hasta la posición inicial.',
      'Repite el ejercicio con la otra pierna.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1649751361457-01d3a696c7e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.activity,
    iconColor: const Color(0xFF2563EB),
    iconBgColor: const Color(0xFFDBEAFE),
    categories: ['Rodilla', 'Flexibilidad'],
    difficulty: 'Fácil',
    targetMuscles: 'Cuádriceps',
  ),
  Exercise(
    id: '2',
    title: 'Extensión de Cadera',
    description: 'Ejercicio enfocado en fortalecer los músculos glúteos y mejorar la estabilidad de la cadera. Ideal para problemas de cadera y fortalecimiento general.',
    duration: '15 min',
    series: 3,
    reps: 10,
    instructions: [
      'Colócate de pie apoyándote en una silla o pared para mantener el equilibrio.',
      'Mantén la espalda recta y el abdomen contraído.',
      'Extiende una pierna hacia atrás sin arquear la espalda.',
      'Mantén la posición durante 2-3 segundos sintiendo el trabajo en el glúteo.',
      'Regresa lentamente a la posición inicial.',
      'Repite con la otra pierna.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.zap,
    iconColor: const Color(0xFF9333EA),
    iconBgColor: const Color(0xFFF3E8FF),
    categories: ['Cadera', 'Fuerza'],
    difficulty: 'Medio',
    targetMuscles: 'Glúteos, Isquiotibiales',
  ),
  Exercise(
    id: '3',
    title: 'Sentadilla Asistida',
    description: 'Sentadilla con apoyo para fortalecer piernas de forma segura. Perfecta para rehabilitación y personas con movilidad reducida.',
    duration: '20 min',
    series: 3,
    reps: 15,
    instructions: [
      'Colócate frente a una silla resistente con los pies separados al ancho de los hombros.',
      'Extiende los brazos hacia adelante para mantener el equilibrio.',
      'Flexiona las rodillas bajando lentamente como si fueras a sentarte.',
      'Toca ligeramente la silla sin sentarte completamente.',
      'Empuja con los talones para volver a la posición inicial.',
      'Mantén la espalda recta durante todo el movimiento.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.dumbbell,
    iconColor: const Color(0xFF16A34A),
    iconBgColor: const Color(0xFFDCFCE7),
    categories: ['Fuerza', 'Rodilla'],
    difficulty: 'Medio',
    targetMuscles: 'Cuádriceps, Glúteos',
  ),
  Exercise(
    id: '4',
    title: 'Estiramiento de Cuádriceps',
    description: 'Estiramiento fundamental para mejorar la flexibilidad del muslo anterior y prevenir lesiones. Recomendado después de ejercicios de fuerza.',
    duration: '10 min',
    series: 2,
    reps: 8,
    instructions: [
      'De pie, apóyate en una pared o silla con una mano.',
      'Flexiona una rodilla llevando el talón hacia el glúteo.',
      'Sujeta el tobillo con la mano del mismo lado.',
      'Mantén las rodillas juntas y la espalda recta.',
      'Sostén el estiramiento durante 20-30 segundos.',
      'Repite con la otra pierna.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.heart,
    iconColor: const Color(0xFFEA580C),
    iconBgColor: const Color(0xFFFED7AA),
    categories: ['Flexibilidad', 'Rodilla'],
    difficulty: 'Fácil',
    targetMuscles: 'Cuádriceps',
  ),
  Exercise(
    id: '5',
    title: 'Rotación de Hombro',
    description: 'Ejercicio suave para mejorar la movilidad del hombro y aliviar tensión. Ideal para rehabilitación de lesiones de hombro.',
    duration: '15 min',
    series: 3,
    reps: 10,
    instructions: [
      'Siéntate o párate con la espalda recta.',
      'Coloca los brazos a los lados del cuerpo.',
      'Levanta los hombros hacia las orejas.',
      'Gira los hombros hacia atrás en círculos amplios.',
      'Realiza 10 repeticiones hacia atrás.',
      'Repite el movimiento hacia adelante.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.rotateCcw,
    iconColor: const Color(0xFF0891B2),
    iconBgColor: const Color(0xFFCFFAFE),
    categories: ['Hombro', 'Flexibilidad'],
    difficulty: 'Fácil',
    targetMuscles: 'Deltoides, Trapecio',
  ),
  Exercise(
    id: '6',
    title: 'Elevación Lateral de Hombro',
    description: 'Fortalece los músculos deltoides laterales para mejorar la estabilidad y fuerza del hombro.',
    duration: '15 min',
    series: 3,
    reps: 12,
    instructions: [
      'De pie con los pies separados al ancho de los hombros.',
      'Brazos a los lados con palmas hacia el cuerpo.',
      'Levanta los brazos lateralmente hasta la altura de los hombros.',
      'Mantén los codos ligeramente flexionados.',
      'Sostén 2 segundos en la posición más alta.',
      'Baja lentamente a la posición inicial.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.moveUp,
    iconColor: const Color(0xFF7C3AED),
    iconBgColor: const Color(0xFFEDE9FE),
    categories: ['Hombro', 'Fuerza'],
    difficulty: 'Medio',
    targetMuscles: 'Deltoides lateral',
  ),
  Exercise(
    id: '7',
    title: 'Puente de Glúteos',
    description: 'Ejercicio fundamental para fortalecer glúteos y zona lumbar. Excelente para estabilidad de cadera y core.',
    duration: '20 min',
    series: 3,
    reps: 15,
    instructions: [
      'Acuéstate boca arriba con las rodillas flexionadas.',
      'Pies apoyados en el suelo, separados al ancho de cadera.',
      'Brazos a los lados con palmas hacia abajo.',
      'Contrae los glúteos y eleva la cadera hacia el techo.',
      'Mantén la posición 3-5 segundos en la parte superior.',
      'Baja lentamente sin tocar completamente el suelo.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.triangleRight,
    iconColor: const Color(0xFFDB2777),
    iconBgColor: const Color(0xFFFCE7F3),
    categories: ['Cadera', 'Fuerza'],
    difficulty: 'Fácil',
    targetMuscles: 'Glúteos, Lumbar',
  ),
  Exercise(
    id: '8',
    title: 'Estiramiento de Isquiotibiales',
    description: 'Estiramiento esencial para la parte posterior del muslo. Mejora la flexibilidad y previene dolor lumbar.',
    duration: '10 min',
    series: 2,
    reps: 6,
    instructions: [
      'Siéntate en el suelo con una pierna extendida.',
      'Flexiona la otra pierna con la planta del pie tocando el muslo interno.',
      'Inclínate hacia adelante desde la cadera.',
      'Alcanza los dedos del pie de la pierna extendida.',
      'Mantén el estiramiento 30 segundos.',
      'Cambia de pierna y repite.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.moveHorizontal,
    iconColor: const Color(0xFF059669),
    iconBgColor: const Color(0xFFD1FAE5),
    categories: ['Flexibilidad', 'Cadera'],
    difficulty: 'Fácil',
    targetMuscles: 'Isquiotibiales',
  ),
  Exercise(
    id: '9',
    title: 'Fortalecimiento de Tobillo',
    description: 'Ejercicios para mejorar la estabilidad y fuerza del tobillo. Ideal para prevención y rehabilitación de esguinces.',
    duration: '15 min',
    series: 3,
    reps: 20,
    instructions: [
      'Siéntate con los pies colgando o sobre una toalla enrollada.',
      'Realiza círculos con el tobillo en sentido horario.',
      'Repite en sentido antihorario.',
      'Flexiona el pie hacia arriba (dorsiflexión).',
      'Extiende el pie hacia abajo (flexión plantar).',
      'Realiza movimientos de lado a lado.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.footprints,
    iconColor: const Color(0xFF0284C7),
    iconBgColor: const Color(0xFFE0F2FE),
    categories: ['Tobillo', 'Flexibilidad'],
    difficulty: 'Fácil',
    targetMuscles: 'Tibial, Peroneos',
  ),
  Exercise(
    id: '10',
    title: 'Plancha Modificada',
    description: 'Versión adaptada de la plancha para fortalecer el core de forma segura. Ideal para principiantes o rehabilitación.',
    duration: '15 min',
    series: 3,
    reps: 5,
    instructions: [
      'Colócate en posición de cuatro puntos (manos y rodillas).',
      'Alinea las manos debajo de los hombros.',
      'Activa el abdomen llevando el ombligo hacia la columna.',
      'Extiende las piernas apoyándote en las rodillas.',
      'Mantén el cuerpo en línea recta desde cabeza hasta rodillas.',
      'Sostén 15-30 segundos y descansa.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    icon: LucideIcons.alignHorizontalJustifyCenter,
    iconColor: const Color(0xFFDC2626),
    iconBgColor: const Color(0xFFFEE2E2),
    categories: ['Fuerza', 'Core'],
    difficulty: 'Medio',
    targetMuscles: 'Core, Abdominales',
  ),
];

// Categorías disponibles
final List<String> exerciseCategories = [
  'Todos',
  'Rodilla',
  'Hombro',
  'Cadera',
  'Fuerza',
  'Flexibilidad',
  'Tobillo',
  'Core',
];
